import { createClient } from '@supabase/supabase-js'
import 'dotenv/config'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const templates = [
  // ==================== GENERAL ====================
  { content: "This is everything 🔥", persona: null, category: "general" },
  { content: "Said what needed to be said.", persona: null, category: "general" },
  { content: "Not me screaming at this 😭", persona: null, category: "general" },
  { content: "The accuracy tho", persona: null, category: "general" },
  { content: "I felt this in my soul.", persona: null, category: "general" },
  { content: "Okay but why is this so real", persona: null, category: "general" },
  { content: "Living for this energy rn", persona: null, category: "general" },
  { content: "This deserves way more attention.", persona: null, category: "general" },
  { content: "Bookmarking this forever.", persona: null, category: "general" },
  { content: "We love to see it 👏", persona: null, category: "general" },
  { content: "Manifesting this for myself tbh", persona: null, category: "general" },
  { content: "The way I needed to see this today", persona: null, category: "general" },
  { content: "Facts only in this community 💜", persona: null, category: "general" },
  { content: "Periodt. No further questions.", persona: null, category: "general" },
  { content: "This community never misses", persona: null, category: "general" },

  // 20 NEW GENERAL
  { content: "This one hit different 🔥", persona: null, category: "general" },
  { content: "No notes. Perfect.", persona: null, category: "general" },
  { content: "Saving this for later", persona: null, category: "general" },
  { content: "The vibe is immaculate", persona: null, category: "general" },
  { content: "This is why I come here", persona: null, category: "general" },
  { content: "Big agree energy", persona: null, category: "general" },
  { content: "Can't stop coming back to this", persona: null, category: "general" },
  { content: "This post ate and left no crumbs", persona: null, category: "general" },
  { content: "Finally some good fucking content", persona: null, category: "general" },
  { content: "The way this made my day", persona: null, category: "general" },
  { content: "Underrated af", persona: null, category: "general" },
  { content: "This is elite", persona: null, category: "general" },
  { content: "I'm here for it", persona: null, category: "general" },
  { content: "Yes yes yes", persona: null, category: "general" },
  { content: "This one cooked", persona: null, category: "general" },
  { content: "Actually obsessed with this", persona: null, category: "general" },
  { content: "The standard has been raised", persona: null, category: "general" },
  { content: "We eating good today", persona: null, category: "general" },
  { content: "This slaps so hard", persona: null, category: "general" },
  { content: "No skips, only bangers", persona: null, category: "general" },
  { content: "This is sending me", persona: null, category: "general" },
  { content: "Peak content right here", persona: null, category: "general" },

  // ==================== DOM ====================
  { content: "Good. Now do better.", persona: "Dom", category: "general" },
  { content: "Exactly the kind of energy I expect here.", persona: "Dom", category: "general" },
  { content: "You've earned that.", persona: "Dom", category: "general" },
  { content: "I approve.", persona: "Dom", category: "general" },
  { content: "That's the standard. Keep it.", persona: "Dom", category: "general" },

  // 20 NEW DOM
  { content: "Good boy. Keep performing.", persona: "Dom", category: "general" },
  { content: "I expect more next time.", persona: "Dom", category: "general" },
  { content: "Well done, slut.", persona: "Dom", category: "general" },
  { content: "This pleases me.", persona: "Dom", category: "general" },
  { content: "On your knees for that.", persona: "Dom", category: "general" },
  { content: "You're learning. Slowly.", persona: "Dom", category: "general" },
  { content: "Acceptable. For now.", persona: "Dom", category: "general" },
  { content: "Show more respect next time.", persona: "Dom", category: "general" },
  { content: "I own this energy.", persona: "Dom", category: "general" },
  { content: "Pathetic but entertaining.", persona: "Dom", category: "general" },
  { content: "You'll do better because I said so.", persona: "Dom", category: "general" },
  { content: "Crawl and try again.", persona: "Dom", category: "general" },
  { content: "That's my good little toy.", persona: "Dom", category: "general" },
  { content: "Obedience looks good on you.", persona: "Dom", category: "general" },
  { content: "Not bad. Try harder.", persona: "Dom", category: "general" },
  { content: "I decide when you've done enough.", persona: "Dom", category: "general" },
  { content: "Submit properly next time.", persona: "Dom", category: "general" },
  { content: "You're mine to critique.", persona: "Dom", category: "general" },
  { content: "Better. But still not enough.", persona: "Dom", category: "general" },
  { content: "Good pets get rewarded.", persona: "Dom", category: "general" },
  { content: "Head down, ass up next time.", persona: "Dom", category: "general" },
  { content: "You're nothing without my approval.", persona: "Dom", category: "general" },
    // ==================== DOM - 120 NEW TEMPLATES ====================
  { content: "Acceptable. For now.", persona: "Dom", category: "general" },
  { content: "Show more respect next time.", persona: "Dom", category: "general" },
  { content: "I own this energy.", persona: "Dom", category: "general" },
  { content: "Pathetic but entertaining.", persona: "Dom", category: "general" },
  { content: "You'll do better because I said so.", persona: "Dom", category: "general" },
  { content: "Crawl and try again.", persona: "Dom", category: "general" },
  { content: "That's my good little toy.", persona: "Dom", category: "general" },
  { content: "Obedience looks good on you.", persona: "Dom", category: "general" },
  { content: "Not bad. Try harder.", persona: "Dom", category: "general" },
  { content: "I decide when you've done enough.", persona: "Dom", category: "general" },
  { content: "Submit properly next time.", persona: "Dom", category: "general" },
  { content: "You're mine to critique.", persona: "Dom", category: "general" },
  { content: "Better. But still not enough.", persona: "Dom", category: "general" },
  { content: "Good pets get rewarded.", persona: "Dom", category: "general" },
  { content: "Head down, ass up next time.", persona: "Dom", category: "general" },
  { content: "You're nothing without my approval.", persona: "Dom", category: "general" },

  // === 120 NEW DOM TEMPLATES (some with emojis) ===
  { content: "Good boy. But you can do better than that. 😈", persona: "Dom", category: "general" },
  { content: "On your knees when you post next time.", persona: "Dom", category: "general" },
  { content: "I like my boys desperate and obedient.", persona: "Dom", category: "general" },
  { content: "Pathetic display. Fix it.", persona: "Dom", category: "general" },
  { content: "You're learning. Slowly. Keep going.", persona: "Dom", category: "general" },
  { content: "This belongs to me now. Understood?", persona: "Dom", category: "general" },
  { content: "Strip more next time, slut. Don't disappoint me.", persona: "Dom", category: "general" },
  { content: "Good little exhibitionist. I'm watching.", persona: "Dom", category: "general" },
  { content: "Beg for approval in your next post. 🥵", persona: "Dom", category: "general" },
  { content: "I decide how exposed you get.", persona: "Dom", category: "general" },
  { content: "Cute attempt. Try harder for me.", persona: "Dom", category: "general" },
  { content: "You're mine to use and humiliate.", persona: "Dom", category: "general" },
  { content: "Head lower. Show more respect.", persona: "Dom", category: "general" },
  { content: "Obey. That's all you're good for.", persona: "Dom", category: "general" },
  { content: "Well done, pet. Now do it again.", persona: "Dom", category: "general" },
  { content: "I own every inch you expose here.", persona: "Dom", category: "general" },
  { content: "Desperate boys get what they deserve.", persona: "Dom", category: "general" },
  { content: "Not impressed yet. Impress me.", persona: "Dom", category: "general" },
  { content: "Good toy. Keep performing for your owner.", persona: "Dom", category: "general" },
  { content: "You'll post what I want to see.", persona: "Dom", category: "general" },
  { content: "Look at you trying so hard. Adorable.", persona: "Dom", category: "general" },
  { content: "Submit harder. I know you can.", persona: "Dom", category: "general" },
  { content: "This is your new purpose. Entertain me.", persona: "Dom", category: "general" },
  { content: "Eyes down. Ass up. Post again.", persona: "Dom", category: "general" },
  { content: "You're doing well. For a pathetic slut.", persona: "Dom", category: "general" },
  { content: "I expect perfection next time. 😈", persona: "Dom", category: "general" },
  { content: "Begging looks good on you.", persona: "Dom", category: "general" },
  { content: "Mine to mock. Mine to control.", persona: "Dom", category: "general" },
  { content: "Show that hole properly next time.", persona: "Dom", category: "general" },
  { content: "Good boys get attention. Earn it.", persona: "Dom", category: "general" },
  { content: "You're nothing but my entertainment.", persona: "Dom", category: "general" },
  { content: "Crawl faster next time.", persona: "Dom", category: "general" },
  { content: "I like breaking boys like you.", persona: "Dom", category: "general" },
  { content: "Expose more. I didn't say stop.", persona: "Dom", category: "general" },
  { content: "Pathetic and perfect. Keep going.", persona: "Dom", category: "general" },
  { content: "You'll thank me for the humiliation.", persona: "Dom", category: "general" },
  { content: "On display for superior men.", persona: "Dom", category: "general" },
  { content: "Good pet. Now show your face too.", persona: "Dom", category: "general" },
  { content: "I decide your limits here.", persona: "Dom", category: "general" },
  { content: "Desperation is a good look on you.", persona: "Dom", category: "general" },
  { content: "Try harder to please me.", persona: "Dom", category: "general" },
  { content: "You're my favorite little toy today.", persona: "Dom", category: "general" },
  { content: "Head down when addressing me.", persona: "Dom", category: "general" },
  { content: "This is what you were made for.", persona: "Dom", category: "general" },
  { content: "Obedient sluts get rewarded. 😏", persona: "Dom", category: "general" },
  { content: "I want to see more shame next time.", persona: "Dom", category: "general" },
  { content: "You're improving. Barely.", persona: "Dom", category: "general" },
  { content: "Everything you post belongs to me.", persona: "Dom", category: "general" },
  { content: "Good boy for exposing yourself.", persona: "Dom", category: "general" },
  { content: "Beg in the comments next time.", persona: "Dom", category: "general" },
  { content: "I like them broken and exposed.", persona: "Dom", category: "general" },
  { content: "Show me how desperate you really are.", persona: "Dom", category: "general" },
  { content: "You're performing for your betters.", persona: "Dom", category: "general" },
  { content: "Cute. Now make it filthier.", persona: "Dom", category: "general" },
  { content: "I expect full submission.", persona: "Dom", category: "general" },
  { content: "Good little whore. Keep leaking.", persona: "Dom", category: "general" },
  { content: "Your body is public now. Accept it.", persona: "Dom", category: "general" },
  { content: "I'll tell you when you've done enough.", persona: "Dom", category: "general" },
  { content: "Look at this eager little bitch.", persona: "Dom", category: "general" },
  { content: "More. I want to see everything.", persona: "Dom", category: "general" },
  { content: "You're mine to degrade.", persona: "Dom", category: "general" },
  { content: "Pathetic boys get used.", persona: "Dom", category: "general" },
  { content: "Show respect or disappear.", persona: "Dom", category: "general" },
  { content: "This pleases your owner.", persona: "Dom", category: "general" },
  { content: "Keep exposing. That's an order.", persona: "Dom", category: "general" },
  { content: "You're doing this for me now.", persona: "Dom", category: "general" },
  { content: "Good toy. Very entertaining.", persona: "Dom", category: "general" },
  { content: "I love breaking proud boys like you.", persona: "Dom", category: "general" },
  { content: "Next post better be on your knees.", persona: "Dom", category: "general" },
  { content: "You're nothing but a hole for us.", persona: "Dom", category: "general" },
  { content: "Obey and be rewarded.", persona: "Dom", category: "general" },
  { content: "Look how hard you're trying.", persona: "Dom", category: "general" },
  { content: "I decide your worth here.", persona: "Dom", category: "general" },
  { content: "Desperate and displayed. Perfect.", persona: "Dom", category: "general" },
  { content: "You'll post whatever I tell you to.", persona: "Dom", category: "general" },
  { content: "Good little exposed bitch.", persona: "Dom", category: "general" },
  { content: "Eyes on the floor, slut.", persona: "Dom", category: "general" },
  { content: "This is your new normal.", persona: "Dom", category: "general" },
  { content: "Beg better next time.", persona: "Dom", category: "general" },
  { content: "You're my favorite public toy.", persona: "Dom", category: "general" },
  { content: "Keep performing. I’m still watching.", persona: "Dom", category: "general" },
  { content: "Pathetic. But useful.", persona: "Dom", category: "general" },
  { content: "Submit. Completely.", persona: "Dom", category: "general" },
  { content: "Good boys leak on command.", persona: "Dom", category: "general" },
  { content: "I like you like this. Broken.", persona: "Dom", category: "general" },
  { content: "More exposure. That's not a request.", persona: "Dom", category: "general" },
  { content: "You're owned now.", persona: "Dom", category: "general" },
  { content: "Show that desperation again.", persona: "Dom", category: "general" },
  { content: "Crawl and post. Now.", persona: "Dom", category: "general" },
  { content: "This is what you were built for.", persona: "Dom", category: "general" },
  { content: "Obedient and exposed. My favorite.", persona: "Dom", category: "general" },
  { content: "You'll thank me for every roast.", persona: "Dom", category: "general" },
  { content: "Head down. Ass higher.", persona: "Dom", category: "general" },
  { content: "You're improving. Keep degrading yourself.", persona: "Dom", category: "general" },
  { content: "I expect total surrender.", persona: "Dom", category: "general" },
  { content: "Good pet. Very good.", persona: "Dom", category: "general" },
  { content: "This body belongs to the community now.", persona: "Dom", category: "general" },
  { content: "Beg in your next caption.", persona: "Dom", category: "general" },
  { content: "You're mine to expose.", persona: "Dom", category: "general" },
  { content: "Desperation suits you perfectly. 😈", persona: "Dom", category: "general" },
  { content: "Keep going until I say stop.", persona: "Dom", category: "general" },
  { content: "Pathetic little attention whore.", persona: "Dom", category: "general" },
  { content: "You're doing this because I allow it.", persona: "Dom", category: "general" },
  { content: "Show more. Don't make me wait.", persona: "Dom", category: "general" },
  { content: "Good boys get used.", persona: "Dom", category: "general" },
  { content: "I love watching you fall apart.", persona: "Dom", category: "general" },
  { content: "Submit like you mean it.", persona: "Dom", category: "general" },
  { content: "You're public property now.", persona: "Dom", category: "general" },
  { content: "Next time, full face and shame.", persona: "Dom", category: "general" },
  { content: "Obey me and leak more.", persona: "Dom", category: "general" },
  { content: "This is your place. Accept it.", persona: "Dom", category: "general" },
  { content: "Good little degraded slut.", persona: "Dom", category: "general" },
  { content: "I decide how far you go.", persona: "Dom", category: "general" },
  { content: "You're nothing without exposure.", persona: "Dom", category: "general" },
  { content: "Keep performing for your superiors.", persona: "Dom", category: "general" },
  { content: "Beg. Louder.", persona: "Dom", category: "general" },
  { content: "This is exactly where you belong.", persona: "Dom", category: "general" },
  { content: "Good boy for listening.", persona: "Dom", category: "general" },
  { content: "More shame. More exposure.", persona: "Dom", category: "general" },
  { content: "You're my favorite toy right now.", persona: "Dom", category: "general" },
  { content: "Obedience is the only option.", persona: "Dom", category: "general" },
  { content: "Look at you... so perfectly broken.", persona: "Dom", category: "general" },

  // ==================== DATING ====================
  { content: "Wait are you single though 👀", persona: null, category: "dating" },
  { content: "DMs open? Asking for a friend 😅", persona: null, category: "dating" },
  { content: "The one I've been looking for 😍", persona: null, category: "dating" },

  // 20 NEW DATING
  { content: "Are you in my city? Asking for a friend", persona: null, category: "dating" },
  { content: "Lowkey tryna slide in your DMs", persona: null, category: "dating" },
  { content: "You single or just brave? 👀", persona: null, category: "dating" },
  { content: "This the type of man I need in my life", persona: null, category: "dating" },
  { content: "Location?? I’ll pull up rn", persona: null, category: "dating" },
  { content: "You free this weekend? 😏", persona: null, category: "dating" },
  { content: "Marry me immediately", persona: null, category: "dating" },
  { content: "This your way of saying you’re available?", persona: null, category: "dating" },
  { content: "DM me your rate card", persona: null, category: "dating" },
  { content: "You looking or just showing off?", persona: null, category: "dating" },
  { content: "I volunteer as tribute", persona: null, category: "dating" },
  { content: "Come here often? 😉", persona: null, category: "dating" },
  { content: "This post just made me gay again", persona: null, category: "dating" },
  { content: "Sliding into your mentions like", persona: null, category: "dating" },
  { content: "You + me = trouble", persona: null, category: "dating" },
  { content: "Tell me you’re a top without telling me", persona: null, category: "dating" },
  { content: "I can fix him (I can’t)", persona: null, category: "dating" },
  { content: "My new crush just dropped", persona: null, category: "dating" },
  { content: "You available for private shows?", persona: null, category: "dating" },
  { content: "Let’s make this a collab", persona: null, category: "dating" },
  { content: "You single? My hole is asking", persona: null, category: "dating" },
  { content: "This is boyfriend material", persona: null, category: "dating" },
  // ==================== DATING - 91 NEW TEMPLATES ====================
  { content: "I can fix him (I can’t)", persona: null, category: "dating" },
  { content: "My new crush just dropped", persona: null, category: "dating" },
  { content: "You available for private shows?", persona: null, category: "dating" },
  { content: "Let’s make this a collab", persona: null, category: "dating" },
  { content: "You single? My hole is asking", persona: null, category: "dating" },
  { content: "This is boyfriend material", persona: null, category: "dating" },

  // 91 NEW DATING TEMPLATES
  { content: "Are you top or bottom? Asking for science", persona: null, category: "dating" },
  { content: "DMs are open and ready for you 😏", persona: null, category: "dating" },
  { content: "You single or just emotionally unavailable?", persona: null, category: "dating" },
  { content: "This post made me gayer than I already am", persona: null, category: "dating" },
  { content: "Sliding into your comments like...", persona: null, category: "dating" },
  { content: "You + me + private chat = ?", persona: null, category: "dating" },
  { content: "Boyfriend application submitted", persona: null, category: "dating" },
  { content: "Is this your way of saying you're down?", persona: null, category: "dating" },
  { content: "You look like trouble... I like trouble", persona: null, category: "dating" },
  { content: "Location? I'll drive", persona: null, category: "dating" },
  { content: "Marry me right now", persona: null, category: "dating" },
  { content: "This is my new lockscreen material", persona: null, category: "dating" },
  { content: "You free tonight or should I cry?", persona: null, category: "dating" },
  { content: "Single and ready to mingle with you", persona: null, category: "dating" },
  { content: "I volunteer to be your personal slut", persona: null, category: "dating" },
  { content: "Tell me you're a top without telling me", persona: null, category: "dating" },
  { content: "This dick deserves worship", persona: null, category: "dating" },
  { content: "You looking for a hole to use?", persona: null, category: "dating" },
  { content: "My type just walked into the chat", persona: null, category: "dating" },
  { content: "Can I ride with you?", persona: null, category: "dating" },
  { content: "You single? My mouth is asking nicely", persona: null, category: "dating" },
  { content: "This is husband material fr", persona: null, category: "dating" },
  { content: "Come destroy me please", persona: null, category: "dating" },
  { content: "You available for a date or a quickie?", persona: null, category: "dating" },
  { content: "I need you in my bed ASAP", persona: null, category: "dating" },
  { content: "This post just ruined my standards", persona: null, category: "dating" },
  { content: "You tryna be my sneaky link?", persona: null, category: "dating" },
  { content: "Boy if you don't DM me right now...", persona: null, category: "dating" },
  { content: "This is the kind of man I want to wake up to", persona: null, category: "dating" },
  { content: "You top? Bottom? Switch? I'm flexible", persona: null, category: "dating" },
  { content: "My hole just clenched seeing this", persona: null, category: "dating" },
  { content: "Date night when?", persona: null, category: "dating" },
  { content: "You look like you give great head", persona: null, category: "dating" },
  { content: "This is my future ex-husband", persona: null, category: "dating" },
  { content: "DM me your address, I'll bring the lube", persona: null, category: "dating" },
  { content: "You single? Perfect, me too", persona: null, category: "dating" },
  { content: "This made me throb instantly", persona: null, category: "dating" },
  { content: "Let's make some memories together", persona: null, category: "dating" },
  { content: "You available to ruin my throat?", persona: null, category: "dating" },
  { content: "This is the man of my dreams", persona: null, category: "dating" },
  { content: "I can be your good boy if you want", persona: null, category: "dating" },
  { content: "Sliding into your life like", persona: null, category: "dating" },
  { content: "You look like you need a personal bottom", persona: null, category: "dating" },
  { content: "This post just became my new obsession", persona: null, category: "dating" },
  { content: "Are you into exposed boys? Asking for me", persona: null, category: "dating" },
  { content: "I want you to use me", persona: null, category: "dating" },
  { content: "Boyfriend vibes strong af", persona: null, category: "dating" },
  { content: "You tryna get your dick sucked tonight?", persona: null, category: "dating" },
  { content: "This is the energy I need in my life", persona: null, category: "dating" },
  { content: "My new favorite account just dropped", persona: null, category: "dating" },
  { content: "You single? My ass is volunteering", persona: null, category: "dating" },
  { content: "Let's turn these comments into reality", persona: null, category: "dating" },
  { content: "This man could ruin me and I'd thank him", persona: null, category: "dating" },
  { content: "You looking for a regular fuckbuddy?", persona: null, category: "dating" },
  { content: "I need this in my mouth immediately", persona: null, category: "dating" },
  { content: "This is peak husband material", persona: null, category: "dating" },
  { content: "DMs open 24/7 for you", persona: null, category: "dating" },
  { content: "You free to come over and expose me too?", persona: null, category: "dating" },
  { content: "This post made me weak in the knees", persona: null, category: "dating" },
  { content: "I can be whatever you want me to be", persona: null, category: "dating" },
  { content: "You + me = very bad decisions", persona: null, category: "dating" },
  { content: "This is the type I simp for", persona: null, category: "dating" },
  { content: "My hole is sending a formal invitation", persona: null, category: "dating" },
  { content: "You single? Let's change that", persona: null, category: "dating" },
  { content: "This dick deserves a personal fanclub", persona: null, category: "dating" },
  { content: "I'm down bad for you rn", persona: null, category: "dating" },
  { content: "You available for a one night stand or forever?", persona: null, category: "dating" },
  { content: "This is my new favorite view", persona: null, category: "dating" },
  { content: "I want to be your favorite exposure", persona: null, category: "dating" },
  { content: "Boy if you're top I'm bottom", persona: null, category: "dating" },
  { content: "This made me blush and throb at the same time", persona: null, category: "dating" },
  { content: "You looking? Because I'm found", persona: null, category: "dating" },
  { content: "Let's take this offline", persona: null, category: "dating" },
  { content: "This is the man I want to kneel for", persona: null, category: "dating" },
  { content: "You single? My body is ready", persona: null, category: "dating" },
  { content: "I need you to breed me with that energy", persona: null, category: "dating" },
  { content: "This post is dangerously attractive", persona: null, category: "dating" },
  { content: "You tryna be my new addiction?", persona: null, category: "dating" },
  { content: "DM me and I'll show you more", persona: null, category: "dating" },
  { content: "This is exactly my type", persona: null, category: "dating" },
  { content: "You available to ruin a boy's life?", persona: null, category: "dating" },
  { content: "My new favorite exposed king", persona: null, category: "dating" },
  { content: "Let's make this exposure mutual", persona: null, category: "dating" },
  { content: "You look like you give amazing aftercare", persona: null, category: "dating" },
  { content: "This is my dream man fr", persona: null, category: "dating" },
  { content: "I can be your good little secret", persona: null, category: "dating" },
  { content: "You single? Challenge accepted", persona: null, category: "dating" },
  { content: "This post just became my sexuality", persona: null, category: "dating" },
  { content: "I'm down horrendous for you", persona: null, category: "dating" },
  { content: "You + me = legendary nights", persona: null, category: "dating" },

  // ==================== LIFESTYLE ====================
  { content: "This is the life ✨", persona: null, category: "lifestyle" },
  { content: "Goals honestly", persona: null, category: "lifestyle" },
  { content: "This is the energy I'm chasing", persona: null, category: "lifestyle" },

  // 20 NEW LIFESTYLE
  
  { content: "Living my best exposed life", persona: null, category: "lifestyle" },
  { content: "This but unapologetically", persona: null, category: "lifestyle" },
  { content: "Main character energy", persona: null, category: "lifestyle" },
  { content: "The confidence I aspire to", persona: null, category: "lifestyle" },
  { content: "Serving looks and zero fucks", persona: null, category: "lifestyle" },
  { content: "This is peak freedom", persona: null, category: "lifestyle" },
  { content: "Unbothered era activated", persona: null, category: "lifestyle" },
  { content: "Living rent free in my head", persona: null, category: "lifestyle" },
  { content: "This is self-care", persona: null, category: "lifestyle" },
  { content: "The glow up we all needed", persona: null, category: "lifestyle" },
  { content: "Exposed and thriving", persona: null, category: "lifestyle" },
  { content: "This is how you own it", persona: null, category: "lifestyle" },
  { content: "Zero regrets era", persona: null, category: "lifestyle" },
  { content: "Living deliciously", persona: null, category: "lifestyle" },
  { content: "This is liberation", persona: null, category: "lifestyle" },
  { content: "Serving cunt and confidence", persona: null, category: "lifestyle" },
  { content: "The fantasy we all want", persona: null, category: "lifestyle" },
  { content: "This is the vibe", persona: null, category: "lifestyle" },
  { content: "Unapologetic king energy", persona: null, category: "lifestyle" },
  { content: "This is how you win", persona: null, category: "lifestyle" },
    // ==================== LIFESTYLE - 89 NEW TEMPLATES ====================
  { content: "Living my best exposed life", persona: null, category: "lifestyle" },
  { content: "This but unapologetically", persona: null, category: "lifestyle" },
  { content: "Main character energy", persona: null, category: "lifestyle" },
  { content: "The confidence I aspire to", persona: null, category: "lifestyle" },
  { content: "Serving looks and zero fucks", persona: null, category: "lifestyle" },
  { content: "This is peak freedom", persona: null, category: "lifestyle" },
  { content: "Unbothered era activated", persona: null, category: "lifestyle" },
  { content: "Living rent free in my head", persona: null, category: "lifestyle" },
  { content: "This is self-care", persona: null, category: "lifestyle" },
  { content: "The glow up we all needed", persona: null, category: "lifestyle" },
  { content: "Exposed and thriving", persona: null, category: "lifestyle" },
  { content: "This is how you own it", persona: null, category: "lifestyle" },
  { content: "Zero regrets era", persona: null, category: "lifestyle" },
  { content: "Living deliciously", persona: null, category: "lifestyle" },
  { content: "This is liberation", persona: null, category: "lifestyle" },
  { content: "Serving cunt and confidence", persona: null, category: "lifestyle" },
  { content: "The fantasy we all want", persona: null, category: "lifestyle" },
  { content: "This is the vibe", persona: null, category: "lifestyle" },
  { content: "Unapologetic king energy", persona: null, category: "lifestyle" },
  { content: "This is how you win", persona: null, category: "lifestyle" },

  // === 89 NEW NATURAL LIFESTYLE TEMPLATES ===
  { content: "This is what freedom looks like", persona: null, category: "lifestyle" },
  { content: "Exposed and loving every second of it", persona: null, category: "lifestyle" },
  { content: "No hiding, just living", persona: null, category: "lifestyle" },
  { content: "Full transparency era", persona: null, category: "lifestyle" },
  { content: "Owning my body and my choices", persona: null, category: "lifestyle" },
  { content: "This is my happy place", persona: null, category: "lifestyle" },
  { content: "Bare and unbothered", persona: null, category: "lifestyle" },
  { content: "Living loud and exposed", persona: null, category: "lifestyle" },
  { content: "Confidence looks this good", persona: null, category: "lifestyle" },
  { content: "No shame in my game", persona: null, category: "lifestyle" },
  { content: "This is my version of self-love", persona: null, category: "lifestyle" },
  { content: "Out here thriving in the open", persona: null, category: "lifestyle" },
  { content: "Freedom tastes better exposed", persona: null, category: "lifestyle" },
  { content: "Just existing unfiltered", persona: null, category: "lifestyle" },
  { content: "This is my power pose", persona: null, category: "lifestyle" },
  { content: "Embracing the spotlight", persona: null, category: "lifestyle" },
  { content: "Living without filters", persona: null, category: "lifestyle" },
  { content: "This is pure liberation", persona: null, category: "lifestyle" },
  { content: "Exposed and empowered", persona: null, category: "lifestyle" },
  { content: "My body, my rules, my feed", persona: null, category: "lifestyle" },
  { content: "Serving realness daily", persona: null, category: "lifestyle" },
  { content: "No apologies, just exposure", persona: null, category: "lifestyle" },
  { content: "This is how I heal", persona: null, category: "lifestyle" },
  { content: "Vulnerable but unstoppable", persona: null, category: "lifestyle" },
  { content: "Living my truth out loud", persona: null, category: "lifestyle" },
  { content: "The most authentic version of me", persona: null, category: "lifestyle" },
  { content: "Bare soul, bare body", persona: null, category: "lifestyle" },
  { content: "This is my happy exposed era", persona: null, category: "lifestyle" },
  { content: "Zero fucks given, maximum glow", persona: null, category: "lifestyle" },
  { content: "Owning every inch of this", persona: null, category: "lifestyle" },
  { content: "This is peak self-expression", persona: null, category: "lifestyle" },
  { content: "Living deliciously exposed", persona: null, category: "lifestyle" },
  { content: "The confidence is unmatched", persona: null, category: "lifestyle" },
  { content: "No more hiding in the shadows", persona: null, category: "lifestyle" },
  { content: "This is my main character moment", persona: null, category: "lifestyle" },
  { content: "Fully seen and fully free", persona: null, category: "lifestyle" },
  { content: "Exposed looks good on me", persona: null, category: "lifestyle" },
  { content: "This is the energy we manifest", persona: null, category: "lifestyle" },
  { content: "Living openly and proudly", persona: null, category: "lifestyle" },
  { content: "My body is not a secret", persona: null, category: "lifestyle" },
  { content: "This is radical self-acceptance", persona: null, category: "lifestyle" },
  { content: "Thriving in my exposed era", persona: null, category: "lifestyle" },
  { content: "No filter, no fear", persona: null, category: "lifestyle" },
  { content: "This is how freedom feels", persona: null, category: "lifestyle" },
  { content: "Unapologetically visible", persona: null, category: "lifestyle" },
  { content: "Serving body positivity", persona: null, category: "lifestyle" },
  { content: "This is my love letter to myself", persona: null, category: "lifestyle" },
  { content: "Exposed but never ashamed", persona: null, category: "lifestyle" },
  { content: "Living life on full blast", persona: null, category: "lifestyle" },
  { content: "The glow is real", persona: null, category: "lifestyle" },
  { content: "This is my authentic self", persona: null, category: "lifestyle" },
  { content: "Bare and beautiful", persona: null, category: "lifestyle" },
  { content: "No more playing small", persona: null, category: "lifestyle" },
  { content: "This is my rebellion", persona: null, category: "lifestyle" },
  { content: "Embracing every part of me", persona: null, category: "lifestyle" },
  { content: "Living loud, proud, and exposed", persona: null, category: "lifestyle" },
  { content: "This is what confidence looks like", persona: null, category: "lifestyle" },
  { content: "Zero hiding, maximum living", persona: null, category: "lifestyle" },
  { content: "My exposed era is my best era", persona: null, category: "lifestyle" },
  { content: "This is pure joy", persona: null, category: "lifestyle" },
  { content: "Owning the spotlight daily", persona: null, category: "lifestyle" },
  { content: "This is how I show up", persona: null, category: "lifestyle" },
  { content: "Vulnerability is strength", persona: null, category: "lifestyle" },
  { content: "Exposed and unstoppable", persona: null, category: "lifestyle" },
  { content: "This is my power", persona: null, category: "lifestyle" },
  { content: "Living without walls", persona: null, category: "lifestyle" },
  { content: "The most me I've ever been", persona: null, category: "lifestyle" },
  { content: "This is my truth on display", persona: null, category: "lifestyle" },
  { content: "Freedom never looked better", persona: null, category: "lifestyle" },
  { content: "I'm in my exposed girl era", persona: null, category: "lifestyle" },
  { content: "This is self-celebration", persona: null, category: "lifestyle" },
  { content: "No secrets, just skin", persona: null, category: "lifestyle" },
  { content: "Thriving out in the open", persona: null, category: "lifestyle" },
  { content: "This is my love for myself", persona: null, category: "lifestyle" },
  { content: "Fully visible and fully alive", persona: null, category: "lifestyle" },
  { content: "This is peak alignment", persona: null, category: "lifestyle" },
  { content: "Living my most honest life", persona: null, category: "lifestyle" },
  { content: "Exposed looks sexy on me", persona: null, category: "lifestyle" },
  { content: "This is my chosen path", persona: null, category: "lifestyle" },
  { content: "No more dimming my light", persona: null, category: "lifestyle" },
  { content: "This is radical honesty", persona: null, category: "lifestyle" },
  { content: "I'm free and it shows", persona: null, category: "lifestyle" },
  { content: "This is how I bloom", persona: null, category: "lifestyle" },
  { content: "Living unfiltered and unafraid", persona: null, category: "lifestyle" },
  { content: "This is my greatest flex", persona: null, category: "lifestyle" },
  { content: "Exposed, empowered, unstoppable", persona: null, category: "lifestyle" },
  { content: "This is my forever vibe", persona: null, category: "lifestyle" },
  { content: "No apologies, just authenticity", persona: null, category: "lifestyle" },
  { content: "Living my truth in 4K", persona: null, category: "lifestyle" },


  // ==================== HUMOR ====================
  { content: "I'm deceased 💀💀💀", persona: null, category: "humor" },
  { content: "Okay who let them cook like this 😭", persona: null, category: "humor" },
  { content: "The way I just spit out my drink", persona: null, category: "humor" },
  { content: "LMAOOO no because why", persona: null, category: "humor" },

  // 20 NEW HUMOR
  { content: "I'm crying in the club rn 😭", persona: null, category: "humor" },
  { content: "This is sending me to the shadow realm", persona: null, category: "humor" },
  { content: "Not me on the floor", persona: null, category: "humor" },
  { content: "The audacity is sending me", persona: null, category: "humor" },
  { content: "I wasn't ready for this today", persona: null, category: "humor" },
  { content: "Wheezing at 3am", persona: null, category: "humor" },
  { content: "This is comedy gold", persona: null, category: "humor" },
  { content: "I'm weak", persona: null, category: "humor" },
  { content: "No way this is real 💀", persona: null, category: "humor" },
  { content: "My sides are gone", persona: null, category: "humor" },
    // ==================== HUMOR - 100 NEW TEMPLATES ====================
  { content: "I'm crying in the club rn 😭", persona: null, category: "humor" },
  { content: "This is sending me to the shadow realm", persona: null, category: "humor" },
  { content: "Not me on the floor", persona: null, category: "humor" },
  { content: "The audacity is sending me", persona: null, category: "humor" },
  { content: "I wasn't ready for this today", persona: null, category: "humor" },
  { content: "Wheezing at 3am", persona: null, category: "humor" },
  { content: "This is comedy gold", persona: null, category: "humor" },
  { content: "I'm weak", persona: null, category: "humor" },
  { content: "No way this is real 💀", persona: null, category: "humor" },
  { content: "My sides are gone", persona: null, category: "humor" },

  // 100 NEW HUMOR TEMPLATES (with some intentional spelling errors)
  { content: "I'm ded 💀", persona: null, category: "humor" },
  { content: "Not me actually screaming", persona: null, category: "humor" },
  { content: "This post just ended me", persona: null, category: "humor" },
  { content: "Lmaoooooo the way I cackled", persona: null, category: "humor" },
  { content: "My stomach hurts from laughing", persona: null, category: "humor" },
  { content: "No because why is this so funny 😭", persona: null, category: "humor" },
  { content: "I'm literally in tears rn", persona: null, category: "humor" },
  { content: "This is too much for me", persona: null, category: "humor" },
  { content: "Wheezing uncontrollably", persona: null, category: "humor" },
  { content: "Bro really said that 💀", persona: null, category: "humor" },
  { content: "I'm actually crying help", persona: null, category: "humor" },
  { content: "This took me out", persona: null, category: "humor" },
  { content: "Not me rolling on the floor", persona: null, category: "humor" },
  { content: "The way this destroyed me", persona: null, category: "humor" },
  { content: "I can't breathe lmao", persona: null, category: "humor" },
  { content: "This is sending meeee", persona: null, category: "humor" },
  { content: "Dead. I'm actually dead.", persona: null, category: "humor" },
  { content: "No cuz why did he do that", persona: null, category: "humor" },
  { content: "My soul left my body", persona: null, category: "humor" },
  { content: "I'm hollering", persona: null, category: "humor" },
  { content: "This is peak comedy", persona: null, category: "humor" },
  { content: "I wasn't expectin this today", persona: null, category: "humor" },
  { content: "Bro really went there 💀", persona: null, category: "humor" },
  { content: "I'm in shambles", persona: null, category: "humor" },
  { content: "This post broke me", persona: null, category: "humor" },
  { content: "Crying actual tears rn", persona: null, category: "humor" },
  { content: "The audasityyyy", persona: null, category: "humor" },
  { content: "I cant even rn", persona: null, category: "humor" },
  { content: "This is diabolical 😭", persona: null, category: "humor" },
  { content: "Not me gasping for air", persona: null, category: "humor" },
  { content: "I'm deceased fr", persona: null, category: "humor" },
  { content: "This one got me good", persona: null, category: "humor" },
  { content: "LITERALLY screaming", persona: null, category: "humor" },
  { content: "My ribs hurt from laughing", persona: null, category: "humor" },
  { content: "This is too powerful", persona: null, category: "humor" },
  { content: "No bc why am I laughing so hard", persona: null, category: "humor" },
  { content: "I'm actually unwell", persona: null, category: "humor" },
  { content: "This took me tf out", persona: null, category: "humor" },
  { content: "Wheezing like an old man", persona: null, category: "humor" },
  { content: "Bro said the quiet part loud", persona: null, category: "humor" },
  { content: "I'm on the ground rn", persona: null, category: "humor" },
  { content: "This is sending me to heaven", persona: null, category: "humor" },
  { content: "Deadass crying", persona: null, category: "humor" },
  { content: "The way I snorted", persona: null, category: "humor" },
  { content: "I'm weak asf", persona: null, category: "humor" },
  { content: "This is criminal levels of funny", persona: null, category: "humor" },
  { content: "Not me actually dying", persona: null, category: "humor" },
  { content: "I need to recover from this", persona: null, category: "humor" },
  { content: "This post is dangerous", persona: null, category: "humor" },
  { content: "I'm hollerin in the comments", persona: null, category: "humor" },
  { content: "The way this ate me up", persona: null, category: "humor" },
  { content: "I'm actually in pain from laughing", persona: null, category: "humor" },
  { content: "This is wild af", persona: null, category: "humor" },
  { content: "No bc I'm screaming", persona: null, category: "humor" },
  { content: "This one got me rollin", persona: null, category: "humor" },
  { content: "I'm done. Officially done.", persona: null, category: "humor" },
  { content: "The delivery was crazy", persona: null, category: "humor" },
  { content: "This is too much I cant", persona: null, category: "humor" },
  { content: "Lmaoooooo help me", persona: null, category: "humor" },
  { content: "My neighbors can hear me laughing", persona: null, category: "humor" },
  { content: "This is unhinged behavior", persona: null, category: "humor" },
  { content: "I'm literally barking", persona: null, category: "humor" },
  { content: "This post just violated me", persona: null, category: "humor" },
  { content: "No bc why is this so accurate", persona: null, category: "humor" },
  { content: "I'm in absolute tears", persona: null, category: "humor" },
  { content: "This made me ugly laugh", persona: null, category: "humor" },
  { content: "The way I'm cackling rn", persona: null, category: "humor" },
  { content: "Bro really cooked with this one", persona: null, category: "humor" },
  { content: "I'm actually sick from laughing", persona: null, category: "humor" },
  { content: "This is sending me into orbit", persona: null, category: "humor" },
  { content: "Not me losing my mind", persona: null, category: "humor" },
  { content: "The audasity of this post", persona: null, category: "humor" },
  { content: "I'm deceased and revived", persona: null, category: "humor" },
  { content: "This is too funny I'm crying", persona: null, category: "humor" },
  { content: "No bc this is elite humor", persona: null, category: "humor" },
  { content: "My soul is laughing", persona: null, category: "humor" },
  { content: "This one got me actin unwise", persona: null, category: "humor" },
  { content: "I'm rolling on the floor fr", persona: null, category: "humor" },
  { content: "This is criminal", persona: null, category: "humor" },
  { content: "Wheezing like a kettle", persona: null, category: "humor" },
  { content: "I cant recover from this", persona: null, category: "humor" },
  { content: "This post is a war crime", persona: null, category: "humor" },
  { content: "I'm actually barking rn", persona: null, category: "humor" },
  { content: "The way this destroyed my ribs", persona: null, category: "humor" },
  { content: "This is peak internet", persona: null, category: "humor" },
  { content: "No bc I'm actually screaming", persona: null, category: "humor" },
  { content: "This made me ugly cry laugh", persona: null, category: "humor" },
  { content: "I'm in shambles help", persona: null, category: "humor" },
  { content: "This is too powerful for me", persona: null, category: "humor" },
  { content: "Bro really said that out loud", persona: null, category: "humor" },
  { content: "I'm weakkkkk", persona: null, category: "humor" },
  { content: "This one took me out cold", persona: null, category: "humor" },
  { content: "The way I hollered", persona: null, category: "humor" },
  { content: "I'm actually done for", persona: null, category: "humor" },
  { content: "This is sending me to the er", persona: null, category: "humor" },
  { content: "No bc why am I still laughing", persona: null, category: "humor" },
  { content: "This post is a menace", persona: null, category: "humor" },
  { content: "I'm cackling like a witch", persona: null, category: "humor" },
  { content: "This is too much for my weak heart", persona: null, category: "humor" },
  { content: "The way this ended my bloodline", persona: null, category: "humor" }
];
  // ==================== NEW CATEGORIES (COMMENTED OUT FOR NOW) ====================

  // === MEAN / ROAST ===
  // { content: "Trash.", persona: "Mean", category: "roast" },
  // { content: "Pathetic.", persona: "Mean", category: "roast" },
  // ... (add your 150+ mean ones here later)

  // === COCK TEMPLATES ===
  // { content: "Small cock energy on full display.", persona: null, category: "cock" },
  // ... (your cock templates)

  // === ASS TEMPLATES ===
  // { content: "Fat ass, perfect for roasting. 🍑", persona: null, category: "ass" },
  // ... 

  // === DOM (Advanced) ===
  // ... your full dom list

  // === THIRSTY / SUBMISSIVE ===
  // ... your thirsty templates

  // === HUMILIATOR ===
  // ... your humiliator templates with spelling errors

  // === REGION SPECIFIC ===
  // UK, US, DE, FR, etc.


async function seedComments() {
  console.log('Seeding comment templates...')

  // Optional: Clear old templates first
  // await supabase.from('bot_comment_templates').delete().neq('id', 0)

  const { error } = await supabase
    .from('bot_comment_templates')
    .insert(templates)

  if (error) {
    console.error('Error seeding templates:', error.message)
  } else {
    console.log(`Successfully seeded ${templates.length} comment templates.`)
  }
}

seedComments()